# Generated by Django 2.2.2 on 2019-06-28 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation_editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation_editor.Chat')),
                ('created_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation_editor.Label')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation_editor.ChatLine')),
            ],
        ),
    ]
