# Generated by Django 2.2.2 on 2019-06-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_editor', '0002_chatline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatline',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
