# Generated by Django 2.2.2 on 2019-06-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_editor', '0003_auto_20190628_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='location',
        ),
    ]
