# Generated by Django 2.2.2 on 2019-07-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_editor', '0004_remove_chat_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatline',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conversation_editor.ChatLine'),
        ),
    ]
