# Generated by Django 2.2.2 on 2019-07-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_editor', '0005_auto_20190701_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatline',
            name='human',
            field=models.BooleanField(default=True),
        ),
    ]
