# Generated by Django 2.2.2 on 2019-07-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_editor', '0009_auto_20190704_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='lbl_upload',
            field=models.FileField(blank=True, null=True, upload_to='labels/'),
        ),
        migrations.AddField(
            model_name='chat',
            name='txt_upload',
            field=models.FileField(blank=True, null=True, upload_to='texts/'),
        ),
    ]
