# Generated by Django 2.1.10 on 2019-07-08 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_editor', '0010_auto_20190705_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
